test:
	go test -cover -race -v .

lint:
	go vet ./...
	golint ./...
	errcheck ./...

gometalinter:
	gometalinter --vendor --cyclo-over=20 --line-length=150 --dupl-threshold=150 --min-occurrences=2 --enable=misspell --deadline=10m ./...
